### ISSUE TITLE
eslintOption "fix" not working

### ISSUE THREAD

**Issue by owenjs** [nabla/vite-plugin-eslint#3]
Hey, big fan of this plugin not stopping the HMR features!

Although I am trying to use the "fix" option for eslint and it's not fixing the fixable errors on saving a source file.

```js
plugins: [
    react(),
    eslintPlugin({
      eslintOptions: {
         fix: true
      }
    })
  ],
```

Want to double check that this is possible before I supply some more source code.

Thank you.

**Comment by ArnaudBarre** [comment]
Thanks for reporting! This is fixed in 1.3.3 🎉

**Comment by owenjs** [comment]
Hi, thanks for the quick fix!

Unfortunately this was still not working for me and after debugging through your code I found the issue.

report.output can be defined even when there are now messages to display.

When this is the case the function is returned too early [here](https://github.com/nabla/vite-plugin-eslint/blob/master/worker.js#L18).

**Comment by ArnaudBarre** [comment]
In my test, there was a warning and a fix so I didn't notice it. Thanks for pointing out, it's fixed it in 1.3.4.

**Comment by owenjs** [comment]
amazing, thank you!
